# ---
# - hosts: localhost
#   connection: local
#   become: true

#   tasks: install apps
#   package:
#   - htop
#   - tmux
#   - vim-nox
#   # job: ansible-pull -o -U https://github.com/vonschutter/RTD-Ansible.git
# tasks to complete before running roles
- hosts: localhost
  tags: always
  become: true
  pre_tasks:
    - name: pre-run | update package cache (arch)
      tags: always
      pacman: update_cache=yes
      changed_when: False
      when: ansible_distribution == "Archlinux"

    - name: pre-run | update package cache (debian, etc)
      tags: always
      apt: update_cache=yes
      changed_when: False
      when: ansible_distribution in ["Debian", "Pop!_OS", "Ubuntu", "Kubuntu"]

    # set up flatpak support
    - name: system setup | tweaks | add flatpak support
      package:
        name: flatpak
        state: present

    - name: Add the GNOME Apps flatpak repository remote
      flatpak_remote:
        name: gnome-apps
        state: present
        flatpakrepo_url: https://sdk.gnome.org/gnome-apps.flatpakrepo

    - name: system setup | tweaks | flatpak | add flathub remote
      tags: packages,flatpak,workstation-packages
      become:
      flatpak_remote:
        name: flathub
        state: present
        flatpakrepo_url: https://flathub.org/repo/flathub.flatpakrepo

    # set up snap support
    - name: system setup | tweaks | install snapd
      package:
        name: snapd
        state: latest
      when: ansible_distribution in ["Pop!_OS", "Ubuntu", "Debian"]

    # distro-specific tasks for ubuntu
    - name: system setup | tweaks | disable apport in config on ubuntu-based hosts
      tags: distro,distro-setup,apport,ubuntu
      lineinfile:
        dest: /etc/default/apport
        regexp: "enabled="
        line: "enabled=0"
      failed_when: false
      when: ansible_distribution in ["Pop!_OS", "Ubuntu"]

    - name: system setup | tweaks | disable and stop apport service on ubuntu-based hosts
      tags: distro,distro-setup,apport,ubuntu
      service:
        name: apport
        enabled: no
        state: stopped
      failed_when: false
      when: ansible_distribution in ["Pop!_OS", "Ubuntu"]
    - name: install packages
      package:
        name:
         - htop
         - tmux
         - vim-nox
         - tilix
      when: ansible_distribution in ["Pop!_OS", "Ubuntu"]
