---
- hosts: localhost
  connection: local
  become: true

  tasks:
  - name: install apps
    package:
    name:
    - htop
    - tmux
    - vim-nox
  # job: ansible-pull -o -U https://github.com/vonschutter/RTD-Ansible.git